Resources:
  CatalogItemVersionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "bookId"
          AttributeType: "S"
        - AttributeName: "version"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "bookId"
          KeyType: "HASH"
        - AttributeName: "version"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "CatalogItemVersions"

  PublishingStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "publishingRecordId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "publishingRecordId"
          KeyType: "HASH"
        - AttributeName: "status"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "PublishingStatus"
